In [9]:

#^ data handling, scaling and accuracy
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import accuracy_score
import pandas as pd

#? supervised machine learning (classification)
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression

#* supervised machine learning (regression)
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score

#& unsupervised machine learning 
from sklearn.cluster import k_means
from sklearn.ensemble import IsolationForest
from sklearn.metrics import silhouette_score
import numpy as np

In [10]:
df2 = pd.read_csv(r'C:\Users\anasq\OneDrive\Desktop\PetroAnalyst\Data_Preprocessing\EDA_data2.csv')

df4 = pd.read_csv(r'C:\Users\anasq\OneDrive\Desktop\PetroAnalyst\Data_Preprocessing\EDA_data.csv')

In [11]:
df2

,date,brent_price,wti_price,GPR_index,USD/INR_rate,LPG_price,petrol_price,diesel_price,brent_lag1,brent_lag3,...,inr_gpr_stress,crude_lpg_impact,lpg_momentum,conflict_intensity,GPR_outlier,brent_outlier,lpg_price_outlier,petrol_price_outlier,diesel_price_outlier,usd_outliers
0,2010/07/01,75.58,76.32,79.38,46.76,378.4,54.45,42.32,74.76,84.82,...,37.12,9.34,5.0,-0.75,0,0,0,0,0,0
1,2010/08/01,77.04,76.60,80.99,46.46,383.4,54.55,39.88,75.58,75.95,...,37.63,9.34,5.0,-0.69,0,0,0,0,0,0
2,2010/09/01,77.84,75.24,71.17,45.87,388.4,54.77,39.98,77.04,74.76,...,32.65,9.19,5.0,-0.95,0,0,0,0,0,0
3,2010/10/01,82.67,81.89,65.99,44.35,393.4,55.47,39.89,77.84,75.58,...,29.27,9.32,5.0,-1.04,0,0,0,0,0,1
4,2010/11/01,85.28,84.25,94.71,44.93,398.4,55.78,39.89,82.67,77.04,...,42.55,9.62,5.0,-0.20,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
184,2025/11/01,63.80,60.06,104.34,88.84,861.7,110.26,97.04,64.54,67.87,...,92.70,6.58,0.0,-0.24,0,0,0,0,0,0
185,2025/12/01,62.54,57.97,131.39,90.04,861.7,110.26,97.04,63.80,67.99,...,118.30,6.53,0.0,0.50,0,0,0,0,0,0
186,2026/01/01,66.60,60.04,167.80,90.90,861.7,107.26,94.04,62.54,64.54,...,152.53,7.03,0.0,1.60,1,0,0,0,0,0
187,2026/02/01,70.89,64.51,121.62,90.75,861.7,107.26,94.04,66.60,63.80,...,110.36,7.47,0.0,0.37,0,0,0,0,0,0
188,2026/03/01,103.13,91.38,297.27,92.82,921.7,101.50,90.62,70.89,62.54,...,275.92,10.39,20.0,5.66,1,1,0,1,0,0

In [12]:
df4

,date,brent_price,wti_price,GPR_index,USD/INR_rate,LPG_price,petrol_price,diesel_price,brent_lag1,brent_lag3,...,inr_gpr_stress,crude_lpg_impact,lpg_momentum,conflict_intensity,GPR_outlier,brent_outlier,lpg_price_outlier,petrol_price_outlier,diesel_price_outlier,usd_outliers
0,2010/07/01,75.58,76.32,79.38,46.7617,378.4,54.45,42.32,74.76,84.82,...,37.1194,9.3400,5.0,-0.7504,0,0,0,0,0,0
1,2010/08/01,77.04,76.60,80.99,46.4605,383.4,54.55,39.88,75.58,75.95,...,37.6284,9.3357,5.0,-0.6856,0,0,0,0,0,0
2,2010/09/01,77.84,75.24,71.17,45.8729,388.4,54.77,39.98,77.04,74.76,...,32.6477,9.1935,5.0,-0.9516,0,0,0,0,0,0
3,2010/10/01,82.67,81.89,65.99,44.3540,393.4,55.47,39.89,77.84,75.58,...,29.2692,9.3207,5.0,-1.0392,0,0,0,0,0,1
4,2010/11/01,85.28,84.25,94.71,44.9315,398.4,55.78,39.89,82.67,77.04,...,42.5546,9.6179,5.0,-0.2021,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
184,2025/11/01,63.80,60.06,104.34,88.8444,861.7,110.26,97.04,64.54,67.87,...,92.7002,6.5780,0.0,-0.2375,0,0,0,0,0,0
185,2025/12/01,62.54,57.97,131.39,90.0350,861.7,110.26,97.04,63.80,67.99,...,118.2970,6.5345,0.0,0.4993,0,0,0,0,0,0
186,2026/01/01,66.60,60.04,167.80,90.9025,861.7,107.26,94.04,62.54,64.54,...,152.5344,7.0258,0.0,1.5997,1,0,0,0,0,0
187,2026/02/01,70.89,64.51,121.62,90.7458,861.7,107.26,94.04,66.60,63.80,...,110.3650,7.4654,0.0,0.3705,0,0,0,0,0,0
188,2026/03/01,103.13,91.38,297.27,92.8182,921.7,101.50,90.62,70.89,62.54,...,275.9207,10.3855,20.0,5.6563,1,1,0,1,0,0

In [23]:

#? supervised (classifier)

classifiers = {
    "Decision Tree": DecisionTreeClassifier(),
    "Random Forest Classifier": RandomForestClassifier(),
    "KNN": KNeighborsClassifier(),
    "Logistic Regression": LogisticRegression()
}

y_classification = df4['LPG_price'].astype(int)


X_r2 = df2
numeric_cols2 = X_r2.select_dtypes(include='number').columns
numeric_cols2 = numeric_cols2.drop('LPG_price') if 'LPG_price' in numeric_cols2 else numeric_cols2
X_scaled2 = MinMaxScaler().fit_transform(X_r2[numeric_cols2])

X_r4 = df4
numeric_cols4 = X_r4.select_dtypes(include='number').columns
numeric_cols4 = numeric_cols4.drop('LPG_price') if 'LPG_price' in numeric_cols4 else numeric_cols4
X_scaled4 = MinMaxScaler().fit_transform(X_r4[numeric_cols4])

classifier_results = []

for name, model in classifiers.items():

    #~ R2 accuracy
    model.fit(X_scaled2, y_classification)
    accuracy2 = accuracy_score(y_classification, model.predict(X_scaled2))

    #~ R4 accuracy
    model.fit(X_scaled4, y_classification)
    accuracy4 = accuracy_score(y_classification, model.predict(X_scaled4))

    diff = abs(accuracy4 - accuracy2) * 100

    classifier_results.append({
        "Classifier Model": name,
        "Round 2 Accuracy": f"{accuracy2 * 100:.2f}%",
        "Round 4 Accuracy": f"{accuracy4 * 100:.2f}%",
        "Difference": f"{diff:.2f}%"
    })

print("--- CLASSIFIER METRICS ---")
print(pd.DataFrame(classifier_results))

--- CLASSIFIER METRICS ---
           Classifier Model Round 2 Accuracy Round 4 Accuracy Difference
0             Decision Tree          100.00%          100.00%      0.00%
1  Random Forest Classifier          100.00%          100.00%      0.00%
2                       KNN           55.56%           55.56%      0.00%
3       Logistic Regression           50.79%           50.79%      0.00%